services:
  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./music_library:/music_library

    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"